-- 创建热门标签视频表
CREATE TABLE `tiktok_hot_tags_video` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `hashtag_id` varchar(50) NOT NULL COMMENT '标签ID',
  `hashtag_name` varchar(255) NOT NULL COMMENT '标签名称',
  `country_id` varchar(10) DEFAULT NULL COMMENT '国家ID',
  `country_value` varchar(100) DEFAULT NULL COMMENT '国家名称',
  `country_label` varchar(50) DEFAULT NULL COMMENT '国家标签',
  `industry_id` bigint DEFAULT NULL COMMENT '行业ID',
  `industry_value` varchar(255) DEFAULT NULL COMMENT '行业名称',
  `industry_label` varchar(100) DEFAULT NULL COMMENT '行业标签',
  `is_promoted` tinyint(1) DEFAULT '0' COMMENT '是否推广',
  `trend_data` json DEFAULT NULL COMMENT '趋势数据JSON',
  `creators_data` json DEFAULT NULL COMMENT '创作者数据JSON',
  `publish_cnt` bigint DEFAULT '0' COMMENT '发布数量',
  `video_views` bigint DEFAULT '0' COMMENT '视频观看量',
  `rank` int DEFAULT '0' COMMENT '排名',
  `rank_diff` int DEFAULT '0' COMMENT '排名变化',
  `rank_diff_type` int DEFAULT '0' COMMENT '排名变化类型',
  `sort_type` varchar(20) NOT NULL COMMENT '排序类型：popular=热门，new=最新',
  `record_date` date NOT NULL COMMENT '记录日期(yyyy-MM-dd)',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hashtag_sort_date` (`hashtag_id`, `sort_type`, `record_date`),
  KEY `idx_record_date` (`record_date`),
  KEY `idx_sort_type` (`sort_type`),
  KEY `idx_rank` (`rank`),
  KEY `idx_hashtag_name` (`hashtag_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='热门标签视频表';