CREATE TABLE IF NOT EXISTS `task_logs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `task_id` bigint(20) DEFAULT NULL COMMENT '任务ID',
  `task_name` varchar(100) NOT NULL COMMENT '任务名称',
  `task_run_id` bigint(20) DEFAULT NULL COMMENT '任务执行记录ID',
  `log_level` varchar(10) NOT NULL COMMENT '日志级别',
  `message` text NOT NULL COMMENT '日志消息',
  `exception` text DEFAULT NULL COMMENT '异常信息',
  `execution_time` int(11) DEFAULT NULL COMMENT '执行耗时(毫秒)',
  `user_count` int(11) DEFAULT NULL COMMENT '处理用户数量',
  `success_count` int(11) DEFAULT NULL COMMENT '成功数量',
  `failed_count` int(11) DEFAULT NULL COMMENT '失败数量',
  `api_calls` int(11) DEFAULT NULL COMMENT 'API调用次数',
  `machine_name` varchar(100) DEFAULT NULL COMMENT '机器名称',
  `thread_id` varchar(50) DEFAULT NULL COMMENT '线程ID',
  `logger_name` varchar(255) DEFAULT NULL COMMENT '日志记录器名称',
  `callsite` varchar(500) DEFAULT NULL COMMENT '调用位置',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_task_name` (`task_name`),
  KEY `idx_task_run_id` (`task_run_id`),
  KEY `idx_log_level` (`log_level`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务服务日志表';